---
title: "The rENA Package"
subtitle: "Text Mining Module 4: A Code Along"
format: 
  revealjs:
    # include-in-header: preview.html
    progress: true
    chalkboard: 
      buttons: false
    preview-links: auto
    # embed-resources: true
    logo: img/LASERlogo_large.png
    width: 1920
    height: 1080
    margin: 0.05
    footer: <a href=https://www.fi.ncsu.edu/projects/laser-institute>LASER Institute
    slide-number: c/t
    theme: [default, css/laser.scss]
execute: 
  freeze: true
resources:
  - demo.pdf
editor: 
  markdown: 
    wrap: 72
---

## Welcome to the LAW Code Along for Module 4

-   The Text Mining course is designed for those seeking an introductory
    understanding of quantifying the text in documents to better
    understand their properties.

-   The following Code Along is a companion to the Module 4 case study's
    **Communicate** stage.

![Figure 2.2 Steps of Data-Intensive Research
Workflow](img/workflow.png){width="60%"}

[@krumm2018]

::: notes
:::

## Module Objectives

This Code Along is about taking our analyses via `rENA` and
communicating it to an audience. By the end of this module we will learn
how to:

-   

::: notes
:::

## Context of the Problem

-   

::: notes
:::

## Research Questions:

-   

::: notes
:::

## Load Libraries

::: panel-tabset
## Packages Needed

-   

## Your Turn

-   Load the `tidyverse` and `tidytext` packages using `library()`

## Answer

```{r echo=TRUE}

```
:::

::: notes
:::

## ❓Questions

-   

Congratulations! You've finished your last Code Along!

# What's Next? {background="#143156"}

::: {style="text-align: left; font-size: 50px"}
-   Complete the *Prepare and Wrangle* part of the [case
    study](https://posit.cloud/spaces/493094/join?access_code=qjsumVzA0HZYgrxOSizVbVPmDs7iHYS32yUQaqDe)

-   Complete the [Epistemic Network Analysis
    badge](https://laser-institute.github.io//text-mining/module-4/tm-4-badge.html)

-   Complete the TM
    [Microcredential](https://laser-institute.github.io//text-mining/module-5/tm-microcredential-badge.html)
:::
