---
title: "Lab 2 Readings: Dictionary-Based Methods"
author: "LASER Institute"
date: today
format: 
  html:
    toc: true
    toc-depth: 4
    toc-location: right
theme:
  light: simplex
  dark: cyborg
editor: visual
#bibliography: lit/references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

Our primary goal is to develop an understanding of dictionary-based approaches for text analysis, the limitations of these methods, and their applications in educational contexts and beyond. You can find readings [here](https://github.com/laser-institute/essential-readings/tree/main/text%20mining/lab%202).

## Readings

##### Required

The article, *Text as data*, is a required read, though you only need to read through Section 5.1 Dictionary-Based Methods. Grimmer and Stewart not only discuss the promises and pitfalls of dictionary methods (pp. 8 - 9), but of automated text analysis more broadly. I also recommend this [video](https://www.youtube.com/watch?v=4xv1ccEUleA) and [brief article](https://cbail.github.io/SICSS_Dictionary-Based_Text_Analysis.html#dictionary-based-quantitative-text-analysis) by Chris Bail of Duke. 

1.  Grimmer, J., & Stewart, B. M. (2013). Text as data: The promise and pitfalls of automatic content analysis methods for political texts. *Political analysis*, *21*(3), 267-297.

##### Choose One (or more if interested)

The first article in this grouping discusses limitations of dictionary-based approaches and foreshadows our introduction to machine learning approaches to classifying text. The next grouping focuses specifically on sentiment analysis and Linguistic Inquiry and Word Count (LIWC). The first website article, *Sentiment analysis: Nearly Everything you need to know*, is very comprehensive and discusses what sentiment analysis actually is, how it works, use cases and applications, resources for diving into specific areas, and data sets for later use. I've also included a few videos for learning more about the topic, one a little [quirky and entertaining(opens in new window)](https://youtu.be/3Pzni2yfGUQ?t=92), others a little more dry but still informative. The remaining three resources focus on LIWC and includes a demo of the proprietary software used to for LIWC. 

1.  Gupta, S. (2018). [Reasons to replace dictionary based text mining with machine learning techniques(opens in new window)](https://hackernoon.com/reasons-to-replace-dictionary-based-text-mining-with-machine-learning-techniques-27537835e1bf). Retrieved from <https://hackernoon.com/reasons-to-replace-dictionary-based-text-mining-with-machine-learning-techniques-27537835e1bf>

2.  MonkeyLearn. (n.d.). [Sentiment analysis: Nearly Everything you need to know](https://monkeylearn.com/sentiment-analysis). Retrieved February 3, 2019, from <https://monkeylearn.com/sentiment-analysis>

3.  Berkowitz, R. (2017). [Introduction to sentiment analysis](https://youtu.be/65RP29Jll80). Retrieved from <https://youtu.be/65RP29Jll80>

4.  Raval, S. (2019). [Sentiment analysis - Data Lit #1](https://youtu.be/3Pzni2yfGUQ?t=92). Retrieved from <https://youtu.be/3Pzni2yfGUQ?t=92>

5.  Tausczik, Y. R., & Pennebaker, J. W. (2009). The psychological meaning of words: LIWC and computerized text analysis methods. Journal of Language and Social Psychology, 29(1), 24--54. <http://doi.org/10.1177/0261927x09351676>

6.  Johar, I. (2016). [LIWC Text Analysis Tutorial](https://youtu.be/lzuMukv8Ql4). Retreived from <https://youtu.be/lzuMukv8Ql4>

\
\
**Sentiment Analysis in Education**\
The first three articles provide a range of applications of SA in education. The first by faculty at Michigan State University demonstrates the use of sentiment analysis to explore tweets from two education conferences and provides an excellent discussion of some general applications for SA in education. Highly recommend this one both as a light read and for the discussion section at the end. The next three articles show how SA has been applied to teacher evaluation surveys, student writing, and online course discussions respectively. The last of which is co-authored by [Tiffany Barnes](https://www.csc.ncsu.edu/people/tmbarnes), professor of Computer Science at NCSU, and provides a nice bridge to our articles on LIWC.  

1.  Crossley, S. A., Mcnamara, D. S., Baker, R. S., Wang, Y., Paquette, L., Barnes, T., & Bergner, Y. (2015). Language to completion - Success in an educational data mining massive open online class(opens in new window). Presented at the 8th International Conference on Educational Data Mining.

2.  Koehler, M. J., Greenhalgh, S., & Zellner, A. (2015). Potential applications of sentiment analysis in educational research and practice -- Is SITE the friendliest conference? (pp. 1--7). Retrieved from <http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.859.5705&rep=rep1&type=pdf>

3.  Munezero, M. , Montero, C. S., Mozgovoy, M., & Sutinen, E. (2013). Exploiting sentiment analysis to track emotions in students' learning diaries(opens in new window). Koli Calling. Retrieved from <https://doi.org/10.1145/2526968.2526984>

4.  Rajput, Q., Haider, S., & Ghani, S. (2016). Lexicon-based sentiment analysis of teachers' evaluation(opens in new window). *Applied Computational Intelligence and Soft Computing*, 2016(3), 1--12. <http://doi.org/10.1155/2016/2385429>

5.  Sigman, B. P., Garr, W., Pongsajapan, R., Selvanadin, M., McWilliams, M., & Bolling, K. (2016). Visualization of Twitter Data in the Classroom. *Decision Sciences Journal of Innovative Education*, *14*(4), 362-381.

LIWC in Education

The last set of articles focus on the use of LIWC. While LIWC is a proprietary tool and there is no official R package for using LIWC -- though the [quanteda package(opens in new window)](https://quanteda.io/) does include a LIWC dictionary -- these articles provide some good examples of how LIWC can can be used to provide insight into educational contexts. The first is a very quick demonstration of how LIWC was applied to analyze tweets from high profile ed policy people. The second article demonstrates the use of both LIWC and [Coh-Metrix(opens in new window)](http://www.cohmetrix.com/) to examine the relationship between linguistic features and ratings of student essays while the third how LIWC can be used to predict course performance. The final resource is a dissertation by Rob Moore, a former NCSU student. Obviously a lengthy read but does provide a nice overview LIWC as well as a detailed process for its application in research.  

1.  Varner, L. K., Roscoe, R. D., & McNamara, D. S. (2013). [Evaluative misalignment of 10th-grade student and teacher criteria for essay quality: An automated textual analysis.(opens in new window)](https://moodle-courses2122.wolfware.ncsu.edu/pluginfile.php/1515909/mod_forum/intro/%20Evaluative%20misalignment%20of%2010th-grade%20student%20and%20teacher%20criteria%20for%20essay%20quality-%20An%20automated%20textual%20analysis.pdf) *Journal of Writing Research, 5(1), 35--59.* <http://doi.org/10.17239/jowr-2013.05.01.2>

2.  Robinson, R. L., Navea, R., & Ickes, W. (2013). [Predicting final course performance from students' written self-introductions: A LIWC analysis(opens in new window)](https://moodle-courses2122.wolfware.ncsu.edu/pluginfile.php/1515909/mod_forum/intro/RobinsonNaveaIckes2012.pdf). *Journal of Language and Social Psychology*. <http://doi.org/10.1177/0261927X13476869>

3.  Moore, R. L. (2017). [Examining the influence of massive open online course pacing condition on the demonstration of cognitive presence.](https://moodle-courses2122.wolfware.ncsu.edu/pluginfile.php/1515909/mod_forum/intro/etd.pdf) 
