---
title: "Intro to Text Mining"
subtitle: "TM Module 1: Essential Readings"
author: "LASER Institute"
date: today 
format:
  html:
    toc: true
    toc-depth: 4
    toc-location: right
theme:
  light: simplex
  dark: cyborg
editor: visual
bibliography: lit/references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

These readings will allow us to build a basic understanding of text
mining as an approach to understand and improve student learning and the
contexts in which learning occurs. The required and self-selected
readings provide an introduction to text mining in the field of
education, and text mining more generally.

## Readings

##### Required

1.  Ferreira‐Mello, R., André, M., Pinheiro, A., Costa, E., & Romero, C.
    (2019). [Text mining in
    education](https://github.com/laser-institute/essential-readings/blob/main/text%20mining/Text%20mining%20in%20education.pdf)
    Wiley Interdisciplinary Reviews: Data Mining and Knowledge
    Discovery, 9(6). <https://doi.org/10.1002/widm.1332>

##### Choose One (or more if interested)

1.  Bail, C. (2018). [An Introduction to Text as
    Data](https://cbail.github.io/textasdata/strengths-weaknesses/rmarkdown/Strengths_and_Weaknesses.html).
    Retrieved
    from <https://cbail.github.io/textasdata/strengths-weaknesses/rmarkdown/Strengths_and_Weaknesses.html>

2.  Bail, C. (2020). [An Introduction to Text
    Analysis](https://youtu.be/pLsC4UyzX_U). Retrieved
    from <https://youtu.be/pLsC4UyzX_U>

3.  Fesler, L., Dee, T., Baker, R., & Evans, B. (2019). [Text as data
    methods for education
    research](https://github.com/laser-institute/essential-readings/blob/main/text%20mining/Text%20as%20Data%20Methods%20for%20Education%20Research.pdf).
    Journal of Research on Educational Effectiveness, 12(4), 707-727.

4.  Temos, J. (2016). [Text analysis for
    teaching](https://mcgrawect.princeton.edu/text-analysis-for-teaching/).
    The McGraw Center. Retrieved
    from <https://mcgrawect.princeton.edu/text-analysis-for-teaching/>

5.  Underwood, T. (2015). [Where to start with text
    mining](https://tedunderwood.com/2012/08/14/where-to-start-with-text-mining/).
    The Stone and the Shell. Retrieved
    from <https://tedunderwood.com/2012/08/14/where-to-start-with-text-mining/>