---
title: 'Lab 4 Readings: Text Classification'
author: "Dr. Shiyan Jiang"
date: "`r format(Sys.Date(),'%B %e, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
editor_options:
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

These readings will allow us to build a basic understanding of text
classification and its application in educational research. The readings
are
[here](https://github.com/laser-institute/essential-readings/tree/main/text%20mining/lab%204).

## Readings

##### Required

1.  [Text preprocessing for
    classification](https://www.youtube.com/watch?v=nxhCyeRR75Q) and
    [Feature extraction](https://www.youtube.com/watch?v=7YacOe4XwhY).
    These two videos by Andre provides a concise introduction on
    preparing texts for classification and turning texts into features
    for building machine learning models.

2.  [Classification](https://smltar.com/mlclassification.html). This
    chapter from Supervised Machine Learning for Text Analysis in R by
    Emil Hvitfeldt And Julia Silge walks you through building a text
    classification model for predicting whether a complaint is about
    "Credit reporting, credit repair services, or other personal
    consumer reports" or not.

3.  [Machine Learning
    ---Fundamentals](https://towardsdatascience.com/machine-learning-basics-part-1-a36d38c7916).
    This blog is a nice introduction to Machine Learning. You will learn
    more about Machine Learning in another course. The core idea in
    Machine Learning is to generate patterns using training data and
    make predictions based on generated patterns.

##### Choose One (or more if interested)

1.  Exploring the relationship between social presence and learners'
    prestige in MOOC discussion forums using automated content analysis
    and social network analysis. The application of text classification
    in MOOC data analysis. 

2.  Design and application of automatic feedback scaffolding in forums
    to promote learning. Leveraging text classification models for
    real-time support. 

3.  Predicting Math Identity Through Language and Click-Stream Patterns
    in a Blended Learning Mathematics Program for Elementary Students.
    The application of text classification for predicting math identity.
    Buidling computational models of identity is a very promising
    research direction.

4.  Analyzing collaborative learning processes automatically: Exploiting
    the advances of computational linguistics in computer-supported
    collaborative learning. Issues of validity and reliability in using
    text classification for collaborative learning process analysis.
