---
title: "tm-learning-lab-3-reach"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# A Tale of Two Standards 

YOUR NAME

## Research Question

Add our question here

## Analysis
Use these bullets to briefly describe our analysis. 

- Bullet 1
- Bullet 2
- Bullet 3

Note: The code below and data read in is need to make our chart for the next slide, but we've set it to not show the code our messages

```{r, echo = FALSE, message=FALSE}
library(tidyverse)
library(here)
sentiment_percents <- read_csv(here("data", "ss-sentiments.csv"))
```

## Findings

```{r, echo=FALSE}
# paste your code used to make stacked bar chart here
sentiment_percents %>%
  ggplot(aes(x = standards, y = percent, fill=sentiment)) +
  geom_bar(width = .8, stat = "identity") +
  facet_wrap(~method, ncol = 1) +
  coord_flip() +
  labs(title = "Public Sentiment on Twitter", 
       subtitle = "The Common Core & Next Gen Science Standards",
       x = "State Standards", 
       y = "Percentage of Words")
```

## Discussion

Add your responses from the Narrate section here